name: Auto close idiot issues

on:
  issues:
    types: [opened]
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.body, '[X] I checked every box') == 'true'
        name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
